### ISSUE TITLE
key up event not triggered because target is blacklisted

### ISSUE THREAD

**Issue by juanantoniofj** [arthurtyukayev/use-keyboard-shortcut#11]
We have a modal component shown up after a shortkeys combination, this modal component will set focus on a textarea after being rendered what disallows the keyupListener to dispatch a `setKeys` action.

Please, correct me if I am wrong but I think `blacklistedTargets`should not be checked on the `keyupListener`.

**Comment by arthurtyukayev** [comment]
The blacklisted targets are a list of targets that ignore the the key combinations. This is mainly used if you enter `Shift + E` in an input for example.
