### ISSUE TITLE
Defining more than one shortcuts results in only firing last defined Shortcut

### ISSUE THREAD

**Issue by euzu** [arthurtyukayev/use-keyboard-shortcut#15]
When i define two shortcuts like 
```
    useKeyboardShortcut(['Control', 'A'], () => doSomethingA());
    useKeyboardShortcut(['Control', 'B'], () => doSomethingB());
```

I can use both Shortcuts, but only doSomethingB() is called.

**Comment by arthurtyukayev** [comment]
@euzu I am not sure that I am able to reproduce this.

**Comment by arthurtyukayev** [comment]
I am going to be pushing an update to hopefully make the entire hook more stable.
