### ISSUE TITLE
State needs to be reset after a successful callback.

### ISSUE THREAD

**Issue by prsidhu** [arthurtyukayev/use-keyboard-shortcut#24]
I'm trying to use a 'Shift + f' key combination to trigger a callback. It works as desired the first time. However, after that the callback gets triggered on pressing either key. It doesn't wait for the combination.

Resetting the reducer's state after a successful callback solves the problem.

**Comment by prsidhu** [comment]
@arthurtyukayev If you could grant me access, I can raise a pull request with the fix for you to review.

**Comment by arthurtyukayev** [comment]
@prsidhu  I appreciate it. You should be able to submit pull requests from forks.

**Comment by arthurtyukayev** [comment]
Thank you for the PR. 

Merged and pushed to NPM.
