### ISSUE TITLE
on Control+T 

### ISSUE THREAD

**Issue by mangukiya12** [arthurtyukayev/use-keyboard-shortcut#52]
I am facing issue in Contol + T short cut as it is opeing new tab, though i had already passed the option for system override true

**Comment by surgeharb** [comment]
Helo @mangukiya12 
I tried to fix using the proposed solution that I sent for that Issue https://github.com/arthurtyukayev/use-keyboard-shortcut/issues/53#issuecomment-1035777486

**Comment by arthurtyukayev** [comment]
I've made some updates to the way that the modifier keys are handled in v1.1.3.

However keep in mind that many of system shortcuts cannot be overridden, and for many of the browsers, Control + T opens a new tab, and cannot be prevented.
