### ISSUE TITLE
Meta + F only works the first time

### ISSUE THREAD

**Issue by dotmlj** [arthurtyukayev/use-keyboard-shortcut#53]
Having used v. 1..0.6 for a while I recently tried updating to the latest version (which fixes another error).

It seems that since v. 1.1.0 Meta + F only works the first time. The second time it goes to the system default "search page".

```
useKeyboardShortcut(['Meta', 'F'], () => handleOpen(), {
    overrideSystem: true,
  });
```

Using React 16.14.0

Thanks!

**Comment by surgeharb** [comment]
I was trying the same and had the same issue. I got it fixed by adding this line in the end of `keydownListener`, after calling the callback function I am resetting the `heldKeys` maybe this would help resolving the issue.
```js
if (heldKeys.current.length === shortcutArray.length) {
    callback(shortcutKeys);
    heldKeys.current = []; // <-- try to add this
}
```

**Comment by arthurtyukayev** [comment]
This was fixed in the latest version, please update

**Comment by dotmlj** [comment]
Thanks, but while the latest version now does catch Meta + F the second+ time, it also always opens the system browser default "search page" when used the second+ time.

In addition to this; now pressing only the Meta key, after first having pressed Meta + F, not executes the same code as when pressing Meta + F.

Tested in Chrome 98.0.4758.80 on macOS.
