### ISSUE TITLE
peerDependencies says this library doesn't work with React 17

### ISSUE THREAD

**Issue by Vinnl** [arthurtyukayev/use-keyboard-shortcut#54]
The `peerDependencies` in package.json currently say this: https://github.com/arthurtyukayev/use-keyboard-shortcut/blob/59b9c4103dbc5c496078a967fd374c59b5fff573/package.json#L15-L16

In other words, only versions higher than 16.8.0, as long as the major version is still 16. React 17 has been out for quite a while though.

**Comment by arthurtyukayev** [comment]
Resolved in #56, will be in the next release.

**Comment by Vinnl** [comment]
Thank you!
