### ISSUE TITLE
The character contained in the shortcut for the input tag could not be entered #use-keyboard-shortcut

### ISSUE THREAD

**Issue by ducnam4298** [arthurtyukayev/use-keyboard-shortcut#68]
I use the library and when I try to enter any key in that shortcut, it cannot be entered. Here is my code: 
![image](https://user-images.githubusercontent.com/45465012/176086969-f05a9c50-6369-4786-ac20-10b5e8d2ea88.png)

**Comment by ducnam4298** [comment]
More specifically it's ctrl +b and ctrl + s I can't type b and s in input tag

**Comment by arthurtyukayev** [comment]
Please read this section of the README, as it's most likely the issue you're facing:
https://github.com/arthurtyukayev/use-keyboard-shortcut#caveats
