### ISSUE TITLE
SyntaxError: Cannot use import statement outside a module in Next.js Project

### ISSUE THREAD

**Issue by chankruze** [arthurtyukayev/use-keyboard-shortcut#70]
```
import useKeyboardShortcut from './lib/useKeyboardShortcut'
^^^^^^

SyntaxError: Cannot use import statement outside a module
```

![image](https://user-images.githubusercontent.com/29806845/186354888-fc3955fb-fefb-4cf6-9c5e-4eb33dfddd07.png)

**Comment by chankruze** [comment]
I am currently importing like this:
```
import useKeyboardShortcut from "../../node_modules/use-keyboard-shortcut/lib/useKeyboardShortcut";
```

**Comment by arthurtyukayev** [comment]
If that works great, however because Next is SSR, you most likely need to use the dynamic imports feature:
https://nextjs.org/docs/advanced-features/dynamic-import
